#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
- v10.15.3

#为codecov添加
env:
  global:
  - CODECOV_TOKEN: "8470fe62-ae4c-4c88-96aa-0efb0bf30c86"

install:
- yarn install
- npm install -g codecov
- npm install -g istanbul
#运行的脚本命令
script:
- yarn run lint
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov


#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
  - master
